# Generated by Django 5.1.1 on 2024-10-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
