# Generated by Django 5.1.1 on 2024-10-06 03:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                (
                    "fecha_publicada",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="autor.autor"
                    ),
                ),
            ],
        ),
    ]
