# Generated by Django 5.1.1 on 2024-10-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="imagen_portada",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="id",
            field=models.AutoField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
