# Generated by Django 5.1.1 on 2024-10-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articulo", "0002_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
