# Generated by Django 5.1.1 on 2024-10-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulo", "0002_articulo_imagen_portada_alter_articulo_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={"verbose_name_plural": "categorias"},
        ),
        migrations.AddField(
            model_name="articulo",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="categoria",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
