# Generated by Django 5.1.1 on 2024-10-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulo", "0003_alter_categoria_options_articulo_slug_categoria_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
